general {
  hide_cursor = true
  grace = 2
  no_fade_in = false
}

background {
  monitor =
  color = rgba(0e0e0eff)
  blur_passes = 0
}

input-field {
  monitor =
  size = 260, 40
  outline_thickness = 1
  dots_size = 0.2
  dots_spacing = 0.4
  dots_center = true
  outer_color = rgba(2a2a2aff)
  inner_color = rgba(0e0e0eff)
  font_color = rgba(d4d4d4ff)
  font_family = CommitMono Nerd Font
  fade_on_empty = false
  placeholder_text =
  check_color = rgba(ff5c00ff)
  fail_color = rgba(a04a32ff)
  fail_text =
  position = 0, -60
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$TIME"
  color = rgba(d4d4d4ff)
  font_size = 72
  font_family = CommitMono Nerd Font
  position = 0, 40
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:18000000] echo "$(date +'%a %d %b' | tr '[:upper:]' '[:lower:]')"
  color = rgba(4a4a4aff)
  font_size = 14
  font_family = CommitMono Nerd Font
  position = 0, -10
  halign = center
  valign = center
}
