monitor = ,preferred,auto,1.5

exec-once = waybar
exec-once = wl-paste --watch cliphist store
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hypridle
exec-once = playerctld daemon

env = LIBVA_DRIVER_NAME,iHD
env = XCURSOR_SIZE,24

input {
  kb_layout = us
  follow_mouse = 1
  accel_profile = flat
}

general {
  gaps_in = 4
  gaps_out = 8
  border_size = 2
  col.active_border = rgba(ff5c00ff)
  col.inactive_border = rgba(2a2a2aff)
  layout = dwindle
}

decoration {
  rounding = 0
  blur {
    enabled = false
  }
  shadow {
    enabled = false
  }
}

animations {
  enabled = true
  bezier = snap, 0.2, 0, 0, 1
  animation = windows, 1, 2, snap
  animation = fade, 1, 2, snap
  animation = workspaces, 1, 2, snap, slidefade 15%
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  background_color = 0xff000000
  focus_on_activate = true
}

workspace = 4, gapsout:16 640 16 640

$mod = SUPER

bind = $mod, RETURN, exec, foot
bind = $mod, D, exec, fuzzel
bind = $mod, B, exec, helium-browser
bind = $mod, Q, killactive
bind = $mod SHIFT, E, exit
bind = $mod CTRL, L, exec, hyprlock
bind = , PRINT, exec, grim -g "$(slurp)" - | satty -f -
bind = $mod, V, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy

bind = $mod, T, togglefloating
bind = $mod, M, fullscreen, 0
bind = $mod, P, pseudo
bind = $mod, S, layoutmsg, togglesplit

bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, J, movewindow, d

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = , XF86AudioPlay, exec, playerctl --player=playerctld,%any play-pause
bind = , XF86AudioPause, exec, playerctl --player=playerctld,%any play-pause
bind = , XF86AudioNext, exec, playerctl --player=playerctld,%any next
bind = , XF86AudioPrev, exec, playerctl --player=playerctld,%any previous
